name: Run tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: XC16.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode 16.1
        run: sudo xcode-select -s /Applications/Xcode-16.1.app
      - name: Run tests
        run: swift test
